/**
 * Booster Skill Packets
 *
 * Structure: BOOSTER_PACKETS[subject][band] = [ { name, info }, ... ]
 * info is optional — items without it get a plain checkbox only.
 * Subjects: 'math' | 'ela'
 * Bands:    'K-2'  | '3-5' | '6-8' | 'HS'
 */
const BOOSTER_PACKETS = {
    math: {
        'K-2': [
            { name: 'Counting and Patterns',        info: 'Number sequence, skip counting, place value, patterns' },
            { name: 'Addition',                     info: 'With and without pictures' },
            { name: 'Subtraction',                  info: 'With and without pictures' },
            { name: 'Add and Subtract Word Problems' },
            { name: 'Length, Height, Weight',       info: 'Measurement' },
            { name: 'Time',                         info: 'Hour, half hour, quarter hour, 5 minutes' },
            { name: 'Money',                        info: 'Coins and dollar bills' },
            { name: 'Geometry',                     info: 'Shapes, shape attributes, partitioning shapes' },
        ],
        '3-5': [
            { name: 'Addition with regrouping' },
            { name: 'Subtraction with regrouping' },
            { name: 'Single Digit Multiplication' },
            { name: 'Simple Division' },
            { name: '1-4 Digit Multiplication' },
            { name: 'Long Division' },
            { name: 'Fractions',                    info: 'Equivalent fractions, comparing and ordering fractions' },
            { name: 'Add and Subtract Fractions',   info: 'Like and unlike denominators' },
            { name: 'Fractions, Decimals & Percent Conversions' },
            { name: 'Money (Decimals)' },
            { name: 'Order of Operations' },
            { name: 'Length, Height, Weight (Measurement)' },
            { name: 'Perimeter and Area' },
            { name: 'Classifying Triangles & Quadrilaterals' },
            { name: 'Angles and Lines' },
        ],
        '6-8': [
            { name: 'Integers' },
            { name: 'Ratio and Percents' },
            { name: 'Unit Rates and Proportions' },
            { name: 'Algebraic Expressions' },
            { name: 'Exponents' },
            { name: 'Polynomials' },
            { name: 'One and Two Step Equations' },
            { name: 'Slope & Rate of Change' },
            { name: 'Area and Volume' },
            { name: 'Pythagorean Theorem' },
            { name: 'Statistics and Probability' },
        ],
        'HS': [
            { name: 'Slope-Intercept Form (y = mx + b)' },
            { name: 'Systems of Equations' },
            { name: 'Multi-Step Equations' },
            { name: 'Domain and Range' },
            { name: 'Functions' },
            { name: 'Polynomials' },
            { name: 'One and Two Step Inequalities' },
        ],
    },

    ela: {
        'K-2': [
            { name: 'Identify and Name Letters' },
            { name: 'Consonant Digraphs (sh, ch, th, ph, ck, …)' },
            { name: 'Consonant Blends (fl, cr, st, str, -nch, …)' },
            { name: 'Silent E' },
            { name: 'Short and Long Vowels' },
            { name: 'Vowel Digraphs/Teams (ai, ea, oa, …)' },
            { name: 'Word Families' },
            { name: 'Beginning, Middle, and Ending Sounds' },
            { name: 'Rhyming' },
            { name: 'Segment & Blend Sounds' },
            { name: 'Syllables' },
            { name: 'Context Clues' },
            { name: 'Reading Comprehension Mixed', info: 'Main idea & details, summarizing, sequencing, author\'s purpose' },
            { name: 'Reading Passages' },
            { name: 'Sight Word Fluency' },
        ],
        '3-5': [
            { name: 'Prefixes & Suffixes' },
            { name: 'Figurative Language' },
            { name: 'Antonyms & Synonyms' },
            { name: 'Multiple Meaning Words' },
            { name: 'Homonyms' },
            { name: 'Context Clues' },
            { name: 'Reading Comprehension Mixed 1', info: 'Main idea & details, author\'s purpose, summarizing, point of view' },
            { name: 'Reading Comprehension Mixed 2', info: 'Inference, cause and effect, compare and contrast' },
            { name: 'Reading Passages' },
            { name: 'Sight Word Fluency' },
            { name: 'Grammar',                      info: 'Nouns, pronouns, verbs, adverbs, adjectives' },
            { name: 'Punctuation & Sentence Writing' },
        ],
        '6-8': [
            { name: 'Prefixes and Suffixes' },
            { name: 'Figurative Language' },
            { name: 'Antonyms and Synonyms' },
            { name: 'Context Clues' },
            { name: '6th Grade Mixed Reading Comprehension', info: 'Craft & structure, integration of knowledge and ideas, key ideas and details, vocabulary and language' },
            { name: '7th Grade Mixed Reading Comprehension', info: 'Craft & structure, integration of knowledge and ideas, key ideas and details, vocabulary and language' },
            { name: '8th Grade Mixed Reading Comprehension', info: 'Craft & structure, integration of knowledge and ideas, key ideas and details, vocabulary and language' },
            { name: 'Punctuation and Sentence Structure' },
            { name: 'Paragraph and Essay Writing' },
        ],
        'HS': [
            { name: '9th Grade Mixed Reading Comprehension',  info: 'Craft & structure, integration of knowledge and ideas, key ideas and details, vocabulary and language' },
            { name: '10th Grade Mixed Reading Comprehension', info: 'Craft & structure, integration of knowledge and ideas, key ideas and details, vocabulary and language' },
            { name: '11th Grade Mixed Reading Comprehension', info: 'Craft & structure, integration of knowledge and ideas, key ideas and details, vocabulary and language' },
            { name: '12th Grade Mixed Reading Comprehension', info: 'Craft & structure, integration of knowledge and ideas, key ideas and details, vocabulary and language' },
        ],
    },
};
